
"""
    Andre Pont - 23164034

    This "Ontology interpreter" was created with much aid from the lab 6 resources,
    it was just slightly modified so that it could read the type of data of the news articles rather than 
    books or university information.
"""
from rdflib import Graph, Namespace
import pandas as pd

def load_news_data_from_rdf_xml(filename):
    """
    Load and extract news data from RDF/XML ontology file
    Returns: pandas DataFrame with news article data
    """
    # Load RDF data using rdflib
    g = Graph()
    g.parse(filename, format='xml')

    # Define the news namespace
    NEWS = Namespace("http://www.example.org/news#")

    # Prepare lists to store the extracted data
    article_ids = []
    categories = []
    headlines = []
    descriptions = []
    places = []

    #SPARQL query to extract all news article details
    query = """
    SELECT ?article ?category ?headline ?description ?place
    WHERE {
        ?article news:category ?category .
        ?article news:headline ?headline .
        ?article news:short_description ?description .
        ?article news:place ?place .
    }
    """

    # Execute the query
    results = g.query(query, initNs={'news': NEWS})

    # Process query results
    for row in results:
        article_id = str(row.article).split("/")[-1]  # Extract article ID from URI
        article_ids.append(article_id)
        categories.append(str(row.category))
        headlines.append(str(row.headline))
        descriptions.append(str(row.description))
        places.append(str(row.place))

    # Create DataFrame
    df = pd.DataFrame({
        'article_id': article_ids,
        'category': categories,
        'headline': headlines,
        'short_description': descriptions,
        'place': places
    })

    return df

#Helper function to make the ontology data retrieved be in csv format so the 
#Naive bayes model can read it and process it properly
#It also prints the results of the data frame generated by the load_news_data_from_rdf_xml function
def parse_to_csv(data_frame):
    print(f"Successfully loaded {len(data_frame)} news articles!")
    print(f"\nDataset shape: {data_frame.shape}")
    print(f"\nFirst 5 articles:")
    print(data_frame.head())

    print(f"\nCategories found:")
    print(data_frame['category'].value_counts())

    data_frame.to_csv('parsed_news_data.csv', index=False)